repos:
    - repo: local
      hooks:
          - id: parcel-quality
            name: Parcel quality suite
            entry: npm run quality
            language: system
            pass_filenames: false
            always_run: true
