{
    "name": "Parcel Transport Management",
    "summary": "Plan and track multi-package parcel transport operations",
    "version": "19.0.1.0.0",
    "category": "Operations",
    "author": "Parcel Transport Management",
    "license": "LGPL-3",
    "depends": ["base", "mail", "uom", "web", "website"],
    "data": [
        "security/parcel_security.xml",
        "security/ir.model.access.csv",
        "data/parcel_sequence.xml",
        "views/public_tracking_templates.xml",
        "views/parcel_wizard_views.xml",
        "views/parcel_shipment_views.xml",
        "views/parcel_package_views.xml",
        "views/parcel_courier_views.xml",
        "views/parcel_zone_views.xml",
        "views/parcel_history_views.xml",
        "views/parcel_settings_views.xml",
        "views/parcel_dashboard_action.xml",
        "views/parcel_menus.xml",
        "views/parcel_report_views.xml",
    ],
    "demo": ["demo/parcel_demo.xml"],
    "assets": {
        "web.assets_backend": [
            "parcel_transport_management/static/src/scss/parcel_native_views.scss",
            "parcel_transport_management/static/src/scss/parcel_dashboard.scss",
            "parcel_transport_management/static/src/js/parcel_dashboard.js",
            "parcel_transport_management/static/src/xml/parcel_dashboard.xml",
        ],
    },
    "application": True,
    "installable": True,
}
